package com.syncbridge.domain.jargon.entity;

import com.syncbridge.domain.user.entity.Role;
import com.syncbridge.global.common.BaseEntity;
import jakarta.persistence.*;
import lombok.AccessLevel;
import lombok.Builder;
import lombok.Getter;
import lombok.NoArgsConstructor;

@Getter
@NoArgsConstructor(access = AccessLevel.PROTECTED)
@Entity
@Table(name = "jargon_translations", indexes = {
    @Index(name = "idx_jargon_role", columnList = "jargon_id, target_role")
})
public class JargonTranslation extends BaseEntity {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "translation_id")
    private Long id;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "jargon_id", nullable = false)
    private JargonTerm jargonTerm;

    @Enumerated(EnumType.STRING)
    @Column(name = "target_role", nullable = false)
    private Role targetRole;

    @Column(name = "easy_definition", nullable = false, columnDefinition = "TEXT")
    private String easyDefinition;

    @Column(name = "business_impact", columnDefinition = "TEXT")
    private String businessImpact;

    @Column(name = "helpful_count", nullable = false)
    private int helpfulCount = 0;

    @Column(name = "unhelpful_count", nullable = false)
    private int unhelpfulCount = 0;

    @Column(name = "auto_generated", nullable = false, columnDefinition = "BOOLEAN DEFAULT FALSE")
    private boolean autoGenerated = false;

    @Column(name = "confidence_score")
    private Double confidenceScore;

    @Builder
    public JargonTranslation(JargonTerm jargonTerm, Role targetRole, String easyDefinition, String businessImpact, boolean autoGenerated, Double confidenceScore) {
        this.jargonTerm = jargonTerm;
        this.targetRole = targetRole;
        this.easyDefinition = easyDefinition;
        this.businessImpact = businessImpact;
        this.helpfulCount = 0;
        this.unhelpfulCount = 0;
        this.autoGenerated = autoGenerated;
        this.confidenceScore = confidenceScore;
    }

    public void addFeedback(boolean isHelpful) {
        if (isHelpful) {
            this.helpfulCount++;
        } else {
            this.unhelpfulCount++;
        }
    }
}
