package com.syncbridge.domain.jargon.service;

import com.syncbridge.domain.user.entity.Role;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.stereotype.Service;
import org.springframework.web.client.RestClient;

import java.util.Map;

@Slf4j
@Service
@RequiredArgsConstructor
public class AiTranslationService {

    private final RestClient restClient;

    @Value("${spring.ai.service-url:http://localhost:8000}")
    private String aiServiceUrl;

    public Map<String, Object> generateTranslation(String keyword, Role role) {
        log.info("Generating AI translation via ai-service for keyword: {} with role: {}", keyword, role);
        
        try {
            Map<String, String> request = Map.of(
                "term", keyword,
                "role", role.name()
            );

            Map<String, Object> response = restClient.post()
                    .uri(aiServiceUrl + "/translate")
                    .body(request)
                    .retrieve()
                    .body(Map.class);

            log.info("AI Service Response: {}", response);
            
            if (response == null) {
                throw new RuntimeException("Empty response from AI service");
            }

            return Map.of(
                "easyDefinition", response.get("easyDefinition"),
                "businessImpact", response.get("businessImpact"),
                "autoGenerated", true,
                "confidenceScore", 0.95
            );
            
        } catch (Exception e) {
            log.error("AI service call failed for keyword: {}", keyword, e);
            return Map.of(
                "easyDefinition", "죄송합니다. 현재 AI 번역 서비스를 일시적으로 사용할 수 없습니다.",
                "businessImpact", "시스템 관리자에게 문의하거나 잠시 후 다시 시도해주세요.",
                "autoGenerated", false
            );
        }
    }
}
