package com.syncbridge.domain.jargon.service;

import com.syncbridge.domain.jargon.dto.JargonTranslationResponse;
import com.syncbridge.domain.jargon.entity.JargonTerm;
import com.syncbridge.domain.jargon.entity.JargonTranslation;
import com.syncbridge.domain.jargon.repository.JargonTermRepository;
import com.syncbridge.domain.jargon.repository.JargonTranslationRepository;
import com.syncbridge.domain.jargon.entity.JargonHit;
import com.syncbridge.domain.jargon.repository.JargonHitRepository;
import com.syncbridge.domain.user.entity.Role;
import com.syncbridge.global.exception.CustomException;
import com.syncbridge.global.exception.ErrorCode;
import com.syncbridge.global.exception.NotFoundException;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import java.util.List;
import java.util.Map;

@Slf4j
@Service
@RequiredArgsConstructor
@Transactional(readOnly = true)
public class JargonService {

    private final JargonTermRepository jargonTermRepository;
    private final JargonTranslationRepository jargonTranslationRepository;
    private final JargonHitRepository jargonHitRepository;
    private final AiTranslationService aiTranslationService;

    public List<String> getAllKeywords() {
        return jargonTermRepository.findAllKeywords();
    }

    @Transactional
    public JargonTranslationResponse translate(String keyword, String roleStr, Long userId) {
        Role targetRole;
        try {
            targetRole = Role.valueOf(roleStr);
        } catch (IllegalArgumentException e) {
            throw new CustomException(ErrorCode.INVALID_INPUT_VALUE, "유효하지 않은 직무입니다: " + roleStr);
        }

        // 1. DB에서 용어(Term) 조회
        JargonTerm jargonTerm = jargonTermRepository.findByKeywordAndIsDeletedFalse(keyword)
                .orElse(null);

        // 2. 용어가 없으면 새로 생성 (AI Fallback으로 이어짐)
        if (jargonTerm == null) {
            jargonTerm = jargonTermRepository.save(new JargonTerm(keyword));
        }

        // 3. 조회 이력 기록 (Hit)
        jargonHitRepository.save(JargonHit.builder()
                .jargonTerm(jargonTerm)
                .userRole(targetRole)
                .userId(userId)
                .build());

        // 4. DB에서 해당 직무의 번역(Translation) 조회
        JargonTranslation translation = jargonTranslationRepository
                .findByJargonTermIdAndTargetRoleAndIsDeletedFalse(jargonTerm.getId(), targetRole)
                .orElse(null);

        // 5. 역할별 번역이 없으면 GENERAL 폴백
        if (translation == null && targetRole != Role.GENERAL) {
            translation = jargonTranslationRepository
                    .findByJargonTermIdAndTargetRoleAndIsDeletedFalse(jargonTerm.getId(), Role.GENERAL)
                    .orElse(null);
        }

        // 6. DB에 없으면 AI에 요청 (Auto-Caching)
        if (translation == null) {
            translation = getAiTranslation(jargonTerm, targetRole);
        }

        return JargonTranslationResponse.from(translation);
    }

    private JargonTranslation getAiTranslation(JargonTerm term, Role role) {
        Map<String, Object> result = aiTranslationService.generateTranslation(term.getKeyword(), role);

        String easyDef = (String) result.getOrDefault("easyDefinition", "설명을 생성할 수 없습니다.");
        String bizImpact = (String) result.getOrDefault("businessImpact", "영향도를 파악할 수 없습니다.");
        boolean autoGenerated = (boolean) result.getOrDefault("autoGenerated", false);
        Double confidenceScore = (Double) result.get("confidenceScore");

        JargonTranslation translation = JargonTranslation.builder()
                .jargonTerm(term)
                .targetRole(role)
                .easyDefinition(easyDef)
                .businessImpact(bizImpact)
                .autoGenerated(autoGenerated)
                .confidenceScore(confidenceScore)
                .build();

        return jargonTranslationRepository.save(translation);
    }

    @Transactional
    public void addFeedback(Long translationId, boolean isHelpful) {
        JargonTranslation translation = jargonTranslationRepository.findById(translationId)
                .orElseThrow(() -> new NotFoundException(ErrorCode.JARGON_NOT_FOUND));
        translation.addFeedback(isHelpful);
        log.info("Feedback added to translation {}: helpful={}", translationId, isHelpful);
    }
}
